# Generated by Django 5.1.1 on 2024-10-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.tipoinsumo')),
            ],
        ),
    ]
