# Generated by Django 5.1.1 on 2024-09-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_alter_category_section_alter_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
