# Generated by Django 5.1.1 on 2024-10-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0003_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='media',
        ),
        migrations.AddField(
            model_name='section',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='section_imagens/'),
        ),
    ]
