# Generated by Django 5.1.1 on 2024-10-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0006_alter_instruction_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
