# Generated by Django 5.1.1 on 2024-10-22 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('infraestrutura', 'Infraestrutura'), ('capacitação', 'Capacitação'), ('gestao', 'Gestão'), ('tecnico', 'Técnico')], default='infraestrutura', max_length=20)),
                ('principal_requisito', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_execucao', 'Em Execução'), ('nao_iniciada', 'Não Iniciada'), ('bloqueada', 'Bloqueada'), ('finalizada', 'Finalizada')], default='nao_iniciada', max_length=20)),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('bizarro', 'Bizarro')], default='medio', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_finalizada', models.DateField(blank=True, null=True)),
                ('demais_integrantes', models.ManyToManyField(blank=True, related_name='dev_projects', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
