# Generated by Django 5.1.1 on 2024-10-22 17:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectdev', '0002_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
